definitions:
  app.ResponseData:
    properties:
      code:
        type: integer
      data: {}
      msg: {}
    type: object
host: localhost:8889
info:
  contact:
    email: support@seagger.io
    name: zxp
    url: http://www.swagger.io/support
  description: An example of gin
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Golang Gin API
  version: "1.0"
paths:
  /api/v1/auth:
    get:
      description: 进行身份验证
      parameters:
      - in: query
        name: password
        required: true
        type: string
      - in: query
        name: username
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ResponseData'
      summary: Get Auth
      tags:
      - 登录
  /api/v1/tags:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.ResponseData'
      summary: Get multiple article tags
swagger: "2.0"
